/**
 * plugins/webfontloader.js
 *
 * webfontloader documentation: https://github.com/typekit/webfontloader
 */
export default defineNuxtPlugin((nuxtApp) => {
  // check https://vuetify-nuxt-module.netlify.app/guide/nuxt-runtime-hooks.html
  nuxtApp.hook('vuetify:before-create', async (_) => {
    // Font loading completely disabled
    console.log('Font loading disabled for stability')
  })
})

// Font loading function removed to avoid Google Fonts dependency
// Generated by Copilot
