// Generated by Copilot
import { getTeams } from './teams';

export default defineEventHandler(async (event) => {
  try {
    const teams = await getTeams(event);
    return teams;
  } catch (error) {
    console.error('Error in teams.get handler:', error);
    throw error;
  }
});