# Stage 1: Build the Vue.js application
FROM node:22 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
# Generated by Copilot: Update caniuse-lite database
RUN npx update-browserslist-db@latest
COPY . .
# Generated by Copilot: Attempt to fix ESLint errors, but ignore failures
RUN npm run lint --fix || true
# Generated by Copilot: Run build and handle errors
RUN npm run build || { echo 'Build failed'; exit 1; }

# Stage 2: Serve the application with Nginx
FROM nginx:1.27 AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY --from=build-stage /app/dist/assets/app-config.js /usr/share/nginx/html-template/app-config.template.js
COPY ./docker-entrypoint.d/*.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/*.sh
EXPOSE 80
# Generated by Copilot: Start Nginx server
CMD ["nginx", "-g", "daemon off;"]