<template>
  <div>
    <v-card>
      <v-toolbar color="indigo" elevation="4">
        <v-toolbar-title>{{ organization }} Teams Metrics</v-toolbar-title>
      </v-toolbar>
      <v-container>
        <!-- Teams Selection -->
        <v-row>
          <v-col cols="12">
            <v-select
              v-model="selectedTeams"
              :items="allTeams"
              item-title="name"
              item-value="slug"
              label="Select Teams"
              multiple
              chips
              clearable
              persistent-hint
              hint="Select teams to filter metrics data"
              @change="handleTeamsChange"
            ></v-select>
          </v-col>
        </v-row>

        <!-- Teams Summary Table -->
        <v-row v-if="metricsReady">
          <v-col cols="12">
            <v-simple-table class="elevation-1 mb-6" fixed-header height="auto">
              <template v-slot:default>
                <thead>
                  <tr>
                    <th class="text-left primary--text" style="width: 15%;">Team</th>
                    <th class="text-center primary--text" style="width: 10%;">Total Suggestions</th>
                    <th class="text-center primary--text" style="width: 10%;">Total Acceptances</th>
                    <th class="text-center primary--text" style="width: 10%;">Lines Suggested</th>
                    <th class="text-center primary--text" style="width: 10%;">Lines Accepted</th>
                    <th class="text-center primary--text" style="width: 10%;">Chat Turns</th>
                    <th class="text-center primary--text" style="width: 10%;">Chat Acceptances</th>
                    <th class="text-center primary--text" style="width: 12.5%;">Acceptance Rate (Count)</th>
                    <th class="text-center primary--text" style="width: 12.5%;">Acceptance Rate (Lines)</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="item in displayedTeamsSummary" :key="item.team">
                    <td class="text-left font-weight-medium">{{ item.team.name }}</td>
                    <td class="text-center">{{ item.total_suggestions_count.toLocaleString() }}</td>
                    <td class="text-center">{{ item.total_acceptances_count.toLocaleString() }}</td>
                    <td class="text-center">{{ item.total_lines_suggested.toLocaleString() }}</td>
                    <td class="text-center">{{ item.total_lines_accepted.toLocaleString() }}</td>
                    <td class="text-center">{{ item.total_chat_turns.toLocaleString() }}</td>
                    <td class="text-center">{{ item.total_chat_acceptances.toLocaleString() }}</td>
                    <td class="text-center">{{ (item.acceptance_rate_by_count * 100).toFixed(2) }}%</td>
                    <td class="text-center">{{ (item.acceptance_rate_by_lines * 100).toFixed(2) }}%</td>
                  </tr>
                  <tr v-if="displayedTeamsSummary.length === 0">
                    <td colspan="9" class="text-center py-4">No data available</td>
                  </tr>
                </tbody>
              </template>
            </v-simple-table>
          </v-col>
        </v-row>

        <!-- Loading State -->
        <v-row v-else>
          <v-col cols="12" class="text-center">
            <v-progress-circular indeterminate color="primary"></v-progress-circular>
          </v-col>
        </v-row>

        <!-- Metrics Viewer -->
        <v-row>
          <v-col cols="12">
            <div v-if="metricsReady" class="metrics-container">
              <div class="metrics-title">
                Detailed Metrics for {{ selectedTeams.length ? selectedTeamNames.join(', ') : 'All Teams' }}
              </div>
              <!-- Generated by Copilot: Using descriptive key based on selected teams -->
              <MetricsViewer 
                v-if="filteredMetrics.length"
                :key="`metrics-${selectedTeams.length ? selectedTeamNames.join('-') : 'all'}`"
                :metrics="filteredMetrics"
              />
              <v-alert
                v-else
                type="info"
                text
              >
                No metrics data available for the selected teams.
              </v-alert>
            </div>
          </v-col>
        </v-row>
      </v-container>
    </v-card>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, computed, onMounted } from 'vue';
import { useRoute } from 'vue-router'; 
import type { Metrics, Team, TeamMetricData, TeamAwareMetrics } from '../model/Metrics';
import MetricsViewer from './MetricsViewer.vue';



//Define props， it is from the parent component
// to pass the teams to this component, it only includes the team name, no team slug
const props = defineProps<{
  teams: string[]
}>();

// Generated by Copilot: Get organization directly from route and config
//const route = useRoute()

console.log('teams in MultiTeamsMetricsViewer:', props.teams);

const config = useRuntimeConfig();

// Generated by Copilot: Use computed property to get organization from route params or config
const organization = computed(() => {
  //output the current route params and query
  console.log('config in MultiTeamsMetricsView', config.public);
  /* console.log('Route params:', route.params);
  console.log('Route query:', route.query);

  if (route.params.org) {
    return route.params.org as string;
  } */
  // the config.public.githubOrg maybe changed in the index.vue since it support route there

  return config.public.githubOrg;
});

// add a team interface to define the structure of team data

// Generated by Copilot: Define reactive variables
const allTeams = ref<Team[]>([]);
const selectedTeams = ref<string[]>([]); // Contains team slugs

const metricsReady = ref(false);

// Generated by Copilot: Update type definition to use TeamAwareMetrics interface
const allMetrics = ref<TeamAwareMetrics[]>([]);

// Generated by Copilot: Update type definition to use TeamAwareMetrics interface for filtered metrics
const filteredMetrics = ref<TeamAwareMetrics[]>([]);

// for table display, it is a summary of metrics for all selected teams, with team info
// Generated by Copilot: Updated type to use TeamMetricData interface
const teamMetrics = ref<TeamMetricData[]>([]);
const error = ref<string | null>(null);

// Generated by Copilot: Function to handle team selection change
const handleTeamsChange = () => {
  // Update filtered metrics when teams selection changes
  if (selectedTeams.value.length > 0) {
    // Generated by Copilot: Filter metrics by selected team slugs instead of team names
    // Since we now have both team name and teamSlug in each metric
    filteredMetrics.value = allMetrics.value.filter(metric => 
      selectedTeams.value.includes(metric.teamSlug)
    );
  } else {
    // Generated by Copilot: Show all metrics when no team is selected
    filteredMetrics.value = [...allMetrics.value];
  }
};

// Generated by Copilot: Function to fetch team metrics data - only called once initially
const fetchTeamsMetrics = async () => {
  try {
    metricsReady.value = false;
    error.value = null;
    
    const teamsToFetch = allTeams.value;
    
    if (!teamsToFetch || teamsToFetch.length === 0) {
      error.value = 'No teams available to fetch metrics';
      metricsReady.value = true;
      return;
    }

    const currentOrg = organization.value;
    
 //   console.log('Fetching metrics for teams:', teamsToFetch, 'in organization:', currentOrg);
    // Generated by Copilot: Using Nuxt's $fetch instead of direct API call
    const response = await $fetch('/api/teams-metrics', {
      method: 'POST',
      body: {
        teams: teamsToFetch,
        organization: currentOrg
      }
    });

    if (response?.teamMetrics?.length > 0) {
      // Generated by Copilot: Store team metrics for table display
      teamMetrics.value = response.teamMetrics;
      
      // Generated by Copilot: Use the metrics array directly from the API response
      // This array already includes both team and teamSlug fields for each metric
      if (Array.isArray(response.metrics)) {
        allMetrics.value = response.metrics;
      } else {
        // Generated by Copilot: Fallback to the old approach if metrics aren't in the expected format
        allMetrics.value = [];
        response.teamMetrics.forEach(teammetric => {
          teammetric.metrics.forEach(metric => {
            const metricWithTeam = structuredClone(metric);
            metricWithTeam.team = teammetric.team.name;
            metricWithTeam.teamSlug = teammetric.team.slug;
            allMetrics.value.push(metricWithTeam);
          });
        });
      }
      
      // Generated by Copilot: Apply initial filtering
      handleTeamsChange();
    } else {
      allMetrics.value = [];
      filteredMetrics.value = [];
      teamMetrics.value = [];
      error.value = 'No metrics data available for the teams';
    }
  } catch (err) {
    allMetrics.value = [];
    filteredMetrics.value = [];
    teamMetrics.value = [];
    error.value = 'Failed to fetch team metrics. Please try again later.';
    console.error('Error fetching team metrics:', err);
  } finally {
    metricsReady.value = true;
  }
};

// Generated by Zhuang
// Modified fetchAllTeams to use $fetch for mounted component compatibility
const fetchAllTeams = async () => {
  try {
    error.value = null;
    
    const currentOrg = organization.value;
    if (!currentOrg) {
      return;
    }

    console.log('Current teams in props:', props.teams);
    console.log('Current teams in config', config.public.githubTeam);
    // Get teams from props first, then from config, fallback to empty string
    // Generated by Zhuang
    const currentTeams = props.teams?.length > 0 
      ? props.teams 
      : (config.public.githubTeam || '');
    console.log('Current teams now is :', currentTeams);

    // console.log('Current public info  in fetchAllTeams in multi-teams:', config.public);
    // console.log('current config.public.teams are:', config.public.githubTeam);
    // const currentTeams = config.public.githubTeam !== undefined ? config.public.githubTeam : '';

    // console.log('Current organization in mulit-teams:', currentOrg);
    // console.log('Current teams in mulit-teams:', currentTeams);
    // console.log('Current teams in config:', config.public.githubTeam);
    // // Generated by Zhuang: Using $fetch as recommended for mounted components
    // // This avoids the "Component is already mounted" warning with useFetch
    // console.log(`Fetching teams for organization: ${currentOrg}`);
    const response = await $fetch('/api/teams', {
      params: { 
      organization: currentOrg,
      teams: currentTeams
      }
    });
    
    if (Array.isArray(response)) {
      // for each team, need to get both team name and team slug
      allTeams.value = response.map(team => ({
          name: team.name,
          slug: team.slug
      }));
      
      // console.log(`Successfully fetched ${allTeams.value.length} teams for ${currentOrg}`);
      if (allTeams.value.length > 0) {
        await fetchTeamsMetrics();
      }
    } else {
      console.error('Teams data is not an array:', response);
      error.value = 'Invalid teams data received';
    }
  } catch (err) {
    console.error('Exception in fetchAllTeams:', err);
    error.value = 'Failed to fetch teams. Please try again later.';
  }
};

// Generated by Copilot: Watch organization changes
watch(organization, async (newOrg, oldOrg) => {
  if (newOrg && newOrg !== oldOrg) {
    // Generated by Copilot: Reset data when organization changes
    selectedTeams.value = []; 
    allTeams.value = []; 
    teamMetrics.value = []; 
    allMetrics.value = []; 
    filteredMetrics.value = []; 
    
    // Generated by Copilot: Fetch teams for new organization
    await fetchAllTeams(); 
    await fetchTeamsMetrics(); // Fetch metrics for the new organization
  }
}, { immediate: true });

// Generated by Copilot: Watch for teams prop changes
watch(() => props.teams, (newTeams) => {
  if (newTeams.length > 0) {
    console.log('Teams prop changed to:', newTeams);
    selectedTeams.value = []; // Reset selection when teams list changes
    allTeams.value = newTeams;
    fetchTeamsMetrics();
  }
}, { immediate: true });

// Generated by Copilot: Add explicit watch for selectedTeams to ensure data updates
watch(() => selectedTeams.value, () => {
  // Generated by Copilot: Update filtered metrics when team selection changes
  handleTeamsChange();
}, { deep: true });

// Generated by Copilot: Load initial data
onMounted(async () => {
  // Fetch all teams for the current organization
  console.log('MultiTeamsMetricsViewer component mounted!');
  console.log('Current config public are', config.public);
  await fetchAllTeams();

  if (props.teams?.length > 0) {
    // Filter teams based on props.teams (matching by team.name)
    const filteredTeams = allTeams.value.filter(team =>
      props.teams.includes(team.name)
    );

    // Update allTeams to the filtered list
    allTeams.value = filteredTeams;
  }

  // Fetch metrics for the filtered or all teams
  await fetchTeamsMetrics();
  
});

// Generated by Copilot: Calculate team summaries
const displayedTeamsSummary = computed(() => {
  if (!teamMetrics.value.length) return [];
  
  // Generated by Copilot: Filter team metrics based on selected team slugs
  const teamsToDisplay = selectedTeams.value.length > 0
    ? teamMetrics.value.filter(tm => selectedTeams.value.includes(tm.team.slug))
    : teamMetrics.value;
  
  return teamsToDisplay.map(tm => {
    const summary = tm.metrics.reduce((acc, metric) => {
      acc.total_suggestions_count += metric.total_suggestions_count;
      acc.total_acceptances_count += metric.total_acceptances_count;
      acc.total_lines_suggested += metric.total_lines_suggested;
      acc.total_lines_accepted += metric.total_lines_accepted;
      acc.total_chat_acceptances += metric.total_chat_acceptances;
      acc.total_chat_turns += metric.total_chat_turns;
      return acc;
    }, {
      team: tm.team, // This is now an object with name and slug
      total_suggestions_count: 0,
      total_acceptances_count: 0,
      total_lines_suggested: 0,
      total_lines_accepted: 0,
      total_chat_acceptances: 0,
      total_chat_turns: 0,
      acceptance_rate_by_count: 0,
      acceptance_rate_by_lines: 0
    });
    
    summary.acceptance_rate_by_count = summary.total_suggestions_count > 0 
      ? summary.total_acceptances_count / summary.total_suggestions_count 
      : 0;
    summary.acceptance_rate_by_lines = summary.total_lines_suggested > 0 
      ? summary.total_lines_accepted / summary.total_lines_suggested 
      : 0;
    
    return summary;
  });
});

// Generated by Copilot: Compute selected team names for display
const selectedTeamNames = computed(() => {
  return allTeams.value
    .filter(team => selectedTeams.value.includes(team.slug))
    .map(team => team.name);
});
</script>

<style scoped>
.v-toolbar-title {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.v-simple-table {
  margin: 0 16px 20px 16px;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  width: calc(100% - 32px);
}

/* Table header styles */
:deep(.v-simple-table > .v-table__wrapper > table > thead > tr > th) {
  background: linear-gradient(to bottom, #f5f7ff, #e8eaf6);
  color: #1a237e;
  font-weight: 600;
  padding: 12px 16px;
  font-size: 0.875rem;
  border-bottom: 2px solid #1a237e;
  white-space: nowrap;
}

/* Table body styles */
:deep(.v-simple-table > .v-table__wrapper > table > tbody > tr > td) {
  padding: 12px 16px;
  font-size: 0.875rem;
  border-bottom: 1px solid #e8eaf6;
}

/* Zebra striping */
:deep(.v-simple-table > .v-table__wrapper > table > tbody > tr:nth-child(even)) {
  background-color: #fafafa;
}

/* Hover effect */
:deep(.v-simple-table > .v-table__wrapper > table > tbody > tr:hover) {
  background-color: rgba(26, 35, 126, 0.04);
}

/* Metrics container styles */
.metrics-container {
  padding: 16px;
  background: #fff;
  border-radius: 4px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.12);
}

.metrics-title {
  font-size: 1.1rem;
  font-weight: 500;
  color: #1a237e;
  margin-bottom: 16px;
  padding-left: 8px;
  border-left: 4px solid #1a237e;
}

/* Select field styles */
:deep(.v-select) {
  margin-bottom: 16px;
}

:deep(.v-select__slot) {
  border-color: #1a237e;
}

:deep(.v-select__selection) {
  color: #1a237e;
}
</style>
