<script lang="ts" setup>
import { useRoute } from 'vue-router';
import './assets/global.css';

// Generated by Copilot - Server-side logging (runs during SSR)
const timestamp = new Date().toISOString();
console.log(`🟢 [SERVER] Page setup START - ${timestamp}`);
console.log(`🟢 [SERVER] Current process type:`, process.server ? 'SERVER' : 'CLIENT');

const route = useRoute();
console.log(`🟢 [SERVER] Route params:`, route.params);
console.log(`🟢 [SERVER] Route query:`, route.query);

// TODO: there might be a better way than overriding the config with route
const config = useRuntimeConfig();

// Generated by Copilot - Detailed config object analysis
console.log(`🟢 [SERVER] Config object details:`, {
  configObjectId: (config as any).$$id || 'no-id',
  isProxy: config.constructor.name === 'Object' ? 'Object' : config.constructor.name,
  publicObjectId: (config.public as any).$$id || 'no-public-id',
  memoryPattern: JSON.stringify(config.public).substring(0, 50)
});

console.log(`🟢 [SERVER] Config before modification:`, {
  githubEnt: config.public.githubEnt,
  githubOrg: config.public.githubOrg,
  githubTeam: config.public.githubTeam,
  scope: config.public.scope
});

// Generated by Copilot - Handle mock mode query parameter
if(route.query.mock) {
  config.public.isDataMocked = true;
  config.public.usingGithubAuth = false;
  console.log(`🟢 [SERVER] Mock mode enabled`);
}

// Generated by Copilot - Mixed approach: modify config for client-server consistency
// while middleware also sets event.context for reliable API calls
if (route.params.ent || route.params.org) {
  console.log(`🟢 [SERVER] Modifying config based on route params for client-server consistency`);
  config.public.githubEnt = route.params.ent as string
  config.public.githubOrg = route.params.org as string
  config.public.githubTeam = route.params.team as string

  // update scope for client-side consistency
  if (route.params.org && route.params.team) {
    config.public.scope = 'team'
    console.log(`🟢 [SERVER] Set scope to: team`);
  } else if (route.params.org) {
    config.public.scope = 'organization'
    console.log(`🟢 [SERVER] Set scope to: organization`);
  } else if (route.params.ent) {
    config.public.scope = 'enterprise'
    console.log(`🟢 [SERVER] Set scope to: enterprise`);
  }
  
  console.log(`🟢 [SERVER] Config modified to ensure client-server data consistency`);
}

console.log(`🟢 [SERVER] Config after modification:`, {
  githubEnt: config.public.githubEnt,
  githubOrg: config.public.githubOrg,
  githubTeam: config.public.githubTeam,
  scope: config.public.scope
});
console.log(`🟢 [SERVER] Page setup END - ${timestamp}`);

computed(() => config.public.version);
</script>

<template>
  <MainComponent />
</template>
