name: cicd

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:

  CICD:
    uses: prosperllc/actions-workflows/.github/workflows/cicd.yaml@main
    secrets: inherit
    with:
      cicd_release_env_ode_enabled: false
      run_auto_tests: false
