# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - copilot-metrics-viewer

on:

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Configure Azure App Settings
      run: |
        az webapp config appsettings set \
          --name copilot-metrics-viewer \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --settings \
            NUXT_PUBLIC_IS_DATA_MOCKED=true \
            NUXT_PUBLIC_SCOPE=organization \
            NUXT_PUBLIC_GITHUB_ORG=mocked-org \
            WEBSITES_PORT=80 \
            NUXT_SESSION_PASSWORD="${{ secrets.NUXT_SESSION_PASSWORD }}"

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'copilot-metrics-viewer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e94dfd38811a421eafe5ce4eee13b68b }}
        images: 'ghcr.io/github-copilot-resources/copilot-metrics-viewer:main'
